"""Add user performance tracking columns

Revision ID: 460e6564da23
Revises: 
Create Date: 2024-11-05 16:27:49.170641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460e6564da23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_level', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('correct_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_correct', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_attempted', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('total_attempted')
        batch_op.drop_column('total_correct')
        batch_op.drop_column('correct_streak')
        batch_op.drop_column('skill_level')

    # ### end Alembic commands ###
